name: Release Binaries

on:
  release:
    types: [published]

jobs:
  build-and-upload:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile vibe_security/cli.py --name vibe-security

      - name: Rename binary for OS
        run: |
          if [[ "${{ matrix.os }}" == "ubuntu-latest" ]]; then
            mv dist/vibe-security dist/vibe-security-linux
          elif [[ "${{ matrix.os }}" == "macos-latest" ]]; then
            mv dist/vibe-security dist/vibe-security-macos
          elif [[ "${{ matrix.os }}" == "windows-latest" ]]; then
            mv dist/vibe-security.exe dist/vibe-security-windows.exe
          fi
        shell: bash

      - name: Upload binary to release
        uses: softprops/action-gh-release@v2
        with:
          files: |
            dist/vibe-security-linux
            dist/vibe-security-macos
            dist/vibe-security-windows.exe
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
