name: Release Binaries

on:
  release:
    types: [published]

jobs:
  upload-binaries:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Install build tools
        run: |
          python -m pip install --upgrade pip
          pip install pyinstaller

      - name: Build with PyInstaller
        run: |
          pyinstaller --onefile vibe_security/cli.py --name vibe-security

      - name: Upload binary to release
        uses: softprops/action-gh-release@v1
        with:
          files: dist/vibe-security*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
